name: Test

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
        puppet:
          - "7"
          - "6"
          - "5"
        exclude:
          - puppet: "6"
            ruby: "3.0"
          - puppet: "5"
            ruby: "3.0"
          - puppet: "5"
            ruby: "2.7"
    name: Ruby ${{ matrix.ruby }} + Puppet ${{ matrix.puppet }}
    env:
      PUPPET_VERSION: "~> ${{ matrix.puppet }}.0"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Show Puppet version
        run: bundle exec puppet --version
      - name: Run tests
        run: bundle exec rake
      - name: Verify gem builds
        run: gem build *.gemspec
